### ISSUE TITLE
Compile libraries against recent Keycloak

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/auth#27]
In order to upgrade Keycloak, the extensions here need to work with the latest version of Keycloak. For at least one of them, this will require `import` changes and recompilation against a recent Keycloak version.

**Comment by bickelj** [comment]
Yes, when trying 22.0.1 with current jars and logging in, it almost works (i.e. I got the text) but then:
```quote
2023-09-08 19:27:45,912 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NoSuchMethodError: 'javax.ws.rs.core.Response org.keycloak.forms.login.LoginFormsProvider.createForm(java.lang.String)'
        at org.philanthropydatacommons.auth.twilio.authenticator.SmsAuthenticator.authenticate(SmsAuthenticator.java:99)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:445)
```

**Comment by bickelj** [comment]
The newly compiled jars are used in both test and prod now.
